// This file stores all the quiz questions. You can easily add more chapters here!
export const quizData = {
    "chapter1": {
        title: "Chapter 1: Network Architecture & OSI Model",
        description: "Test your knowledge on basic network topologies, OSI model, and core concepts.",
        questions: [
            { question: "Which layer of the OSI model is responsible for logical addressing and routing?", options: ["Data Link", "Network", "Transport", "Presentation"], correctAnswer: 1 },
            { question: "At which OSI layer do switches and MAC addresses typically operate?", options: ["Layer 1", "Layer 2", "Layer 3", "Layer 4"], correctAnswer: 1 },
            { question: "Which network topology connects all devices to a single central device?", options: ["Ring", "Mesh", "Star", "Bus"], correctAnswer: 2 },
            { question: "What is the primary purpose of a DNS server?", options: ["Assign IPs", "Resolve domain names to IPs", "Filter traffic", "Encrypt traffic"], correctAnswer: 1 },
            { question: "Which port does HTTPS typically use?", options: ["80", "443", "22", "53"], correctAnswer: 1 },
            { question: "Which describes a Local Area Network (LAN)?", options: ["Country-wide", "Single building/campus", "Storage network", "Secure tunnel"], correctAnswer: 1 },
            { question: "What is the function of a router in a network?", options: ["Connect local devices", "Forward packets between networks", "Provide Wi-Fi", "Block traffic"], correctAnswer: 1 },
            { question: "Which OSI layer provides reliable data transfer using TCP?", options: ["Network", "Data Link", "Transport", "Application"], correctAnswer: 2 },
            { question: "What topology offers the highest redundancy?", options: ["Bus", "Star", "Mesh", "Ring"], correctAnswer: 2 },
            { question: "Which device operates at Layer 1 of the OSI model?", options: ["Switch", "Router", "Hub", "Firewall"], correctAnswer: 2 },
            { question: "What port does HTTP use?", options: ["443", "80", "21", "25"], correctAnswer: 1 },
            { question: "Which layer handles data formatting and encryption?", options: ["Application", "Presentation", "Session", "Transport"], correctAnswer: 1 },
            { question: "A network that connects multiple LANs across a large region is a:", options: ["PAN", "WLAN", "WAN", "SAN"], correctAnswer: 2 },
            { question: "What port is used for SSH?", options: ["21", "22", "23", "3389"], correctAnswer: 1 },
            { question: "Which protocol is connectionless and operates at the Transport layer?", options: ["TCP", "UDP", "IP", "ICMP"], correctAnswer: 1 },
            { question: "What is the length of an IPv4 address?", options: ["16 bits", "32 bits", "64 bits", "128 bits"], correctAnswer: 1 },
            { question: "What is the length of an IPv6 address?", options: ["32 bits", "64 bits", "128 bits", "256 bits"], correctAnswer: 2 },
            { question: "Which layer is responsible for establishing, maintaining, and terminating sessions?", options: ["Network", "Transport", "Session", "Application"], correctAnswer: 2 },
            { question: "What type of cable uses light to transmit data?", options: ["Coaxial", "UTP", "STP", "Fiber Optic"], correctAnswer: 3 },
            { question: "Which topology connects all nodes in a closed loop?", options: ["Star", "Mesh", "Ring", "Bus"], correctAnswer: 2 },
            { question: "What does MTU stand for?", options: ["Maximum Transfer Unit", "Maximum Transmission Unit", "Minimum Transfer Unit", "Multiple Transmission Units"], correctAnswer: 1 },
            { question: "Which layer provides the user interface to network services?", options: ["Presentation", "Session", "Application", "Data Link"], correctAnswer: 2 },
            { question: "What protocol operates at Port 25?", options: ["FTP", "SSH", "SMTP", "DNS"], correctAnswer: 2 },
            { question: "What does CSMA/CD stand for?", options: ["Carrier Sense Multiple Access / Collision Detection", "Carrier Signal Multiple Access / Collision Domain", "Central System Multiple Access / Collision Detection", "Carrier Sense Multiple Access / Collision Domain"], correctAnswer: 0 },
            { question: "Which layer converts frames into bits?", options: ["Network", "Data Link", "Physical", "Transport"], correctAnswer: 2 },
            { question: "What port does Telnet use?", options: ["21", "22", "23", "25"], correctAnswer: 2 },
            { question: "A PAN (Personal Area Network) is most commonly associated with:", options: ["Fiber", "Bluetooth", "Ethernet", "Wi-Fi"], correctAnswer: 1 },
            { question: "Which device divides collision domains?", options: ["Hub", "Repeater", "Switch", "Cable"], correctAnswer: 2 },
            { question: "Which port is used by DNS?", options: ["22", "53", "80", "110"], correctAnswer: 1 },
            { question: "Which layer attaches a MAC address to a packet?", options: ["Network", "Data Link", "Physical", "Transport"], correctAnswer: 1 },
            { question: "Which technology uses 802.11 standards?", options: ["Ethernet", "Bluetooth", "Wi-Fi", "WiMAX"], correctAnswer: 2 },
            { question: "What port does RDP (Remote Desktop) use?", options: ["3389", "1433", "8080", "443"], correctAnswer: 0 }
        ]
    },
    "chapter2": {
        title: "Chapter 2: Network Protocols & Operations",
        description: "Questions covering common networking protocols, IP addressing, and operations.",
        questions: [
            { question: "Which protocol automatically assigns IP addresses?", options: ["DNS", "DHCP", "ARP", "NTP"], correctAnswer: 1 },
            { question: "What command tests basic network reachability?", options: ["tracert", "ipconfig", "ping", "netstat"], correctAnswer: 2 },
            { question: "Which transport protocol is connection-oriented?", options: ["UDP", "TCP", "ICMP", "IP"], correctAnswer: 1 },
            { question: "What is the purpose of ARP?", options: ["Translate IP to MAC", "Assign IPs", "Transfer files", "Sync clocks"], correctAnswer: 0 },
            { question: "Which protocol provides secure file transfer?", options: ["TFTP", "FTP", "SFTP", "Telnet"], correctAnswer: 2 },
            { question: "Which Class A IP range is reserved for loopback testing?", options: ["10.x.x.x", "127.x.x.x", "169.254.x.x", "192.168.x.x"], correctAnswer: 1 },
            { question: "What is APIPA?", options: ["Automatic Private IP Addressing", "Advanced Protocol IP Allocation", "Automated Public IP Allocation", "Automatic Port IP Assignment"], correctAnswer: 0 },
            { question: "Which protocol synchronizes network clocks?", options: ["NTP", "SNMP", "SMTP", "FTP"], correctAnswer: 0 },
            { question: "What command shows the route packets take to a destination?", options: ["ping", "tracert / traceroute", "ipconfig", "nslookup"], correctAnswer: 1 },
            { question: "Which protocol is used to monitor and manage network devices?", options: ["SMTP", "SNMP", "NTP", "SIP"], correctAnswer: 1 },
            { question: "What is a default gateway?", options: ["A switch port", "The router interface leading out of the local network", "A firewall rule", "A DNS server IP"], correctAnswer: 1 },
            { question: "What translates private IPs to public IPs?", options: ["DHCP", "DNS", "NAT", "ARP"], correctAnswer: 2 },
            { question: "What command displays MAC addresses on a Windows PC?", options: ["ipconfig /all", "ping", "tracert", "netsh"], correctAnswer: 0 },
            { question: "Which port does TFTP use?", options: ["21", "22", "69", "80"], correctAnswer: 2 },
            { question: "What is a VLAN?", options: ["Virtual Local Area Network", "Variable Length Area Network", "Virtual Link Access Node", "Variable Local Area Network"], correctAnswer: 0 },
            { question: "Which protocol is used for VoIP signaling?", options: ["SMTP", "SIP", "NTP", "FTP"], correctAnswer: 1 },
            { question: "What does the subnet mask do?", options: ["Encrypts IP addresses", "Determines network and host portions of an IP", "Assigns MAC addresses", "Routes packets to the internet"], correctAnswer: 1 },
            { question: "What port does POP3 use?", options: ["25", "110", "143", "443"], correctAnswer: 1 },
            { question: "What port does IMAP use?", options: ["25", "110", "143", "443"], correctAnswer: 2 },
            { question: "Which command queries DNS servers for troubleshooting?", options: ["ping", "ipconfig", "nslookup", "arp -a"], correctAnswer: 2 },
            { question: "What is the IPv6 loopback address?", options: ["127.0.0.1", "::1", "FE80::", "FF00::"], correctAnswer: 1 },
            { question: "What does a DHCP Discover packet do?", options: ["Finds a DNS server", "Searches for an available DHCP server", "Renews an IP lease", "Assigns a MAC address"], correctAnswer: 1 },
            { question: "Which IP class uses a default subnet mask of 255.255.0.0?", options: ["Class A", "Class B", "Class C", "Class D"], correctAnswer: 1 },
            { question: "What is the broadcast address for network 192.168.1.0/24?", options: ["192.168.1.1", "192.168.1.254", "192.168.1.255", "192.168.2.0"], correctAnswer: 2 },
            { question: "What is the purpose of ICMP?", options: ["File transfer", "Error reporting and diagnostics (like ping)", "Domain resolution", "Encryption"], correctAnswer: 1 },
            { question: "Which protocol uses UDP port 67 and 68?", options: ["DNS", "DHCP", "TFTP", "SNMP"], correctAnswer: 1 },
            { question: "Which IP range is link-local (APIPA) in IPv4?", options: ["10.0.0.0/8", "172.16.0.0/12", "169.254.0.0/16", "192.168.0.0/16"], correctAnswer: 2 },
            { question: "What does Spanning Tree Protocol (STP) prevent?", options: ["Broadcast storms / Switching loops", "DDoS attacks", "IP conflicts", "MAC spoofing"], correctAnswer: 0 },
            { question: "Which command clears the DNS cache in Windows?", options: ["ipconfig /renew", "ipconfig /flushdns", "arp -d", "netstat -r"], correctAnswer: 1 },
            { question: "What is the administrative distance of a directly connected route?", options: ["0", "1", "90", "120"], correctAnswer: 0 },
            { question: "Which routing protocol uses hop count as its primary metric?", options: ["OSPF", "EIGRP", "RIP", "BGP"], correctAnswer: 2 }
        ]
    },
    "chapter3": {
        title: "Chapter 3: CompTIA Network+ Practice Questions",
        description: "A mixed bag of 30 CompTIA Network+ practice questions.",
        questions: [
            { question: "The IEEE standard 802.3af states the specifications for which of the following?", options: ["Quality of Service", "VLANs", "Routing tables", "Power over Ethernet"], correctAnswer: 3 },
            { question: "A user's remote marketing server has changed IP address schemes and now the user can no longer access it. The user further discovers that the distant end still has access to them. Which of the following is a possible cause?", options: ["SNMP strings need to be added", "Firewall rules need to be configured", "Port bonding on the interface needs to be enabled", "The switch has lost power"], correctAnswer: 1 },
            { question: "Which of the following is a network device that allows remote users access to a network?", options: ["DNS server", "Content filter", "Load balancer", "VPN concentrator"], correctAnswer: 3 },
            { question: "A technician suspects that a virus has been introduced on the network. Which network resource is BEST used to confirm this problem?", options: ["Syslog", "SNMP", "Network sniffer", "Environmental monitor"], correctAnswer: 2 },
            { question: "A user reports a network connectivity problem. Which of the following steps should the technician perform FIRST?", options: ["Determine a probable cause", "Implement the solution of the cause", "Test the theory of the cause", "Identify the problem"], correctAnswer: 3 },
            { question: "Which of the following protocols is used by a web browser to display a web page?", options: ["SMTP", "FTP", "HTTP", "IMAP4"], correctAnswer: 2 },
            { question: "Which of the following record types is required for every server in a DNS environment?", options: ["AAA", "MX", "SFP", "A"], correctAnswer: 3 },
            { question: "The frequency of the 802.11b and 802.11g is which of the following?", options: ["2.4GHz", "900MHz", "5GHz", "1800MHz"], correctAnswer: 0 },
            { question: "Which of the following uses port 22 by default?", options: ["TELNET", "SSH", "FTP", "DNS"], correctAnswer: 1 },
            { question: "A user is unable to connect to a network with encryption. The user is able to see the network and has the correct passphrase. Which of the following is MOST likely the problem?", options: ["Encryption type", "SSID mismatch", "Standard mismatch", "Signal strength"], correctAnswer: 0 },
            { question: "A technician is troubleshooting a UTP cable that has been suspected of having problems due to EMI. Which of the following cables should the technician use without adding new equipment to the network?", options: ["Singlemode fiber", "STP", "Plenum", "Multimode fiber"], correctAnswer: 1 },
            { question: "Which of the following network topologies describes a network where packets of data are transmitted from one computer to another in a circular fashion?", options: ["Ring", "Mesh", "Bus", "Star"], correctAnswer: 0 },
            { question: "Which of the following defines the length of time a device retains its IP address for?", options: ["Scope", "Reservation", "Subnet", "Lease"], correctAnswer: 3 },
            { question: "Which of the following virtual devices is the BEST to use to host a company's website?", options: ["PBX", "Server", "Switch", "Desktop"], correctAnswer: 1 },
            { question: "A cable standard that includes a fire-retardant jacket is:", options: ["coaxial cable", "fiber cable", "plenum cable", "UTP cable"], correctAnswer: 2 },
            { question: "A new drop is active according to the network administrator. A technician takes a laptop to the new drop to test connectivity and gets an intermittent signal. Which of the following tools could the technician use to test the line?", options: ["Environmental monitor", "Toner probe", "Protocol analyzer", "Cable tester"], correctAnswer: 3 },
            { question: "An administrator works for a law firm in an office building in a major city. After installing a new wireless access point, the administrator secures the device using WPA and then connects to it using a laptop. Which of the following would be the logical NEXT step in securing the device?", options: ["Add a second SSID broadcast to the access point and name it the same as a neighboring company", "Change the wireless encryption type to WEP", "Remove the antennas", "Check neighboring offices for connectivity and reduce the signal strength appropriately"], correctAnswer: 3 },
            { question: "An administrator is asked to set up a home office for a user who would like to connect to the Internet and share files with all six computers in the home. Which of the following are the MINIMUM requirements if the user refuses to install wireless devices and all computers contain working network cards?", options: ["Hub, Cables, Firewall", "Firewall, Router, Cables", "Switch, Firewall, Cables", "Router, Switch, Cables"], correctAnswer: 3 },
            { question: "The command netstat –n will display which of the following?", options: ["Ethernet statistics", "IP address", "Address and port numbers in numerical form", "Protocol statistics"], correctAnswer: 2 },
            { question: "A business has expanded to additional floors in the building. The expansion only calls for switches and patch panels to be installed. Which of the following would the network manager need to locate?", options: ["MDF", "Demarc", "Smart jack", "IDF"], correctAnswer: 3 },
            { question: "A network administrator needs to implement a new wireless network for a coffee shop. The shop wants to allow users wireless access from anywhere in the shop, but not outside. Which of the following should be the GREATEST concern for the administrator?", options: ["Channel", "Compatibility", "WAP placement", "Interference"], correctAnswer: 2 },
            { question: "A user receives an information message on their computer stating a duplicate address exists. A technician would discover that which of the following is true?", options: ["Wrong gateway", "Evil twin", "IP address conflict", "Wrong subnet mask"], correctAnswer: 2 },
            { question: "Which of the following layers is the presentation layer?", options: ["Layer 3", "Layer 5", "Layer 6", "Layer 7"], correctAnswer: 2 },
            { question: "When differentiating hubs from switches, which of the following is FALSE?", options: ["Hubs have multiple collision domains.", "Switches have multiple collision domains.", "Switches have a single broadcast domain.", "Hubs have a single broadcast domain."], correctAnswer: 0 },
            { question: "Which of the following connector types are MOST commonly associated with phone jacks?", options: ["RJ-11", "ST", "RJ-45", "SC"], correctAnswer: 0 },
            { question: "Which of the following 802.11 channels operates above 5GHz?", options: ["a", "b", "g", "i"], correctAnswer: 0 },
            { question: "Which of the following allows the LONGEST distance using single-mode fiber?", options: ["10GBaseSR", "10GBaseER", "10GBaseSW", "10GBaseLW"], correctAnswer: 1 },
            { question: "A switch can separate different subnets by configuring:", options: ["VTP on each switch", "trunking on all ports", "VLANs throughout the ports", "STP on the main ports"], correctAnswer: 2 },
            { question: "At which of the following layers does the HTTP protocol operate?", options: ["Layer 1", "Layer 4", "Layer 5", "Layer 7"], correctAnswer: 3 },
            { question: "Which of the following WAN technology types provides the FASTEST speeds?", options: ["OC3", "SDSL", "ADSL", "T3"], correctAnswer: 0 }
        ]
    },
    "chapter4": {
        title: "Chapter 4: Cram Quiz - Network Topologies",
        description: "Practice questions on network topologies and architectures.",
        questions: [
            { question: "You have been asked to install a network that will give the network users the greatest amount of fault tolerance. Which of the following network topologies would you choose?", options: ["Star/hub and spoke", "Ring", "Mesh", "Bus"], correctAnswer: 2 },
            { question: "Which of the following topologies allows for network expansion with the least amount of disruption for the current network users?", options: ["Bus", "Ring", "LAN", "Star/hub and spoke"], correctAnswer: 3 },
            { question: "Which network topology offers the greatest level of redundancy but has the highest implementation cost?", options: ["Wireless mesh", "Wired mesh", "Hybrid star", "Bus network"], correctAnswer: 1 },
            { question: "What traffic pattern refers to data that travels outside the datacenter or enterprise?", options: ["East-to-West", "North-to-South", "On-premises", "West-to-South"], correctAnswer: 1 },
            { question: "What layer in three-tier hierarchical model network architecture is considered the backbone of a network?", options: ["Core layer", "Distribution/aggregation layer", "Access/edge layer", "Application layer"], correctAnswer: 0 },
            { question: "Which topology utilizes a dedicated connection between two endpoints?", options: ["Mesh", "Spine and leaf", "Point to point", "Star"], correctAnswer: 2 },
            { question: "Which topology is commonly used in datacenter environments for high scalability and flexibility?", options: ["Ad hoc", "Hybrid", "Star", "Spine and leaf"], correctAnswer: 3 },
            { question: "This network architecture includes simplicity, cost savings (via a reduced number of network devices and switches), efficient communication (with fewer layers, there are fewer network hops between devices), and scalability (it can scale relatively well for medium-sized networks and datacenters with a moderate number of devices). Which network architecture is being described?", options: ["Collapsed core", "NFV", "ToR switching", "Four-tier hierarchical model"], correctAnswer: 0 },
            { question: "Which layer in the three-tier hierarchical model network architecture facilitates traffic between end devices and the rest of the network?", options: ["Core layer", "Distribution layer", "Point-to-point layer", "Access layer"], correctAnswer: 3 }
        ]
    }
};
